name: Windows

defaults:
  run:
    shell: bash


on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main


jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Add clang path to $PATH env
        run: echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
      
      - name: Passes clang-format
        run: clang-format -i examples/*.cpp && clang-format -i tests/*.cpp && clang-format -i tests/*.hpp && clang-format -i benchmarks/*.cpp && git diff-index --quiet HEAD
      
      - name: Run CMake setup
        working-directory: ./
        run: mkdir build/ && cd build/ && cmake ../
      
      - name: Build examples
        working-directory: ./build
        run: make examples
      
      - name: Build tests
        working-directory: ./build
        run: make tests  

      - name: Build benchmarks
        working-directory: ./build
        run: make benchmarks

      - name: Run tests
        working-directory: ./
        run: ./build/tests/test